### ISSUE TITLE
Rimuovere il main.pdf

### ISSUE THREAD

**Issue by arn4** [SciSNS-2017/Sistemi-Dinamici#4]
Il main causa cancri quando faccio pull. Dato che non é particolarmente utile per ora e che quando pubblicheremo sarebbe bello metterlo in un posto molto piú sensato, potremmo toglierlo.
@marco-venuti mi dispiace

**Comment by marco-venuti** [comment]
Toglilo pure. Mi sembra Zoratti abbia parlato (però sarebbe su Gitlab)
dell'esistenza di una cosa che compila i file caricati secondo determinate
istruzioni, potremmo dare un'occhiata in futuro.
